services:
  app:
    build: .
    restart: always
    container_name: worker-geral
    env_file:
      - .env
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    volumes:
      - ./config:/usr/src/app/config
      - ./logs:/usr/src/app/logs

  # Exemplo para outro cliente:
  #
  # worker-cliente-a:
  #   build: .
  #   restart: always
  #   container_name: worker-cliente-a
  #   env_file:
  #     - .env.cliente-a
  #   ports:
  #     - "3001:3001"
  #   volumes:
  #     - ./config/cliente-a:/usr/src/app/config
  #     - ./logs/cliente-a:/usr/src/app/logs
